# 配置MySQL配置文件
- name: Config MySQL Config
  template: src=my.cnf6.j2 dest=/etc/my.cnf
  when: ansible_distribution_major_version == "6"
  notify: Restart MySQL

- name: Config Mariadb Config
  template: src=my.cnf7.j2 dest=/etc/my.cnf
  when: ansible_distribution_major_version == "7"
  notify: Restart Mariadb
