- name: Create Config Dir
  file: name={{ INSTALL_DIR }}nginx/conf/conf.d state=directory

- name: Copy Config Template
  template: src=nginx.conf.j2 dest={{ INSTALL_DIR }}nginx/conf/nginx.conf
  notify: Restart Nginx

