# PHP启动文件配置
- name: Copy Service Template7
  template: src=php-fpm.service.j2 dest=/usr/lib/systemd/system/php-fpm.service
  when: ansible_distribution_major_version == "7"

- name: Copy Service Template6
  template: src=php-fpm.init.j2 dest=/etc/init.d/php-fpm mode=755
  when: ansible_distribution_major_version == "6"

- name: Start Php
  service: name=php-fpm state=started enabled=yes
